In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('train_and_test2.csv')

print(df.head())

In [4]:
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [5]:
df.shpae

AttributeError: 'DataFrame' object has no attribute 'shpae'

In [6]:
df.shape

(1309, 28)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(25)
memory usage: 286.5 KB

In [8]:
df.describe()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
count,1309.000000,1309.000000,1309.000000,1309.000000,1309.000000,1309.0,1309.0,1309.0,1309.0,1309.0,...,1309.0,1309.0,1309.0,1309.000000,1309.0,1309.0,1307.000000,1309.0,1309.0,1309.000000
mean,655.000000,29.503186,33.281086,0.355997,0.498854,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.294882,0.0,0.0,1.492731,0.0,0.0,0.261268
std,378.020061,12.905241,51.741500,0.478997,1.041658,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.837836,0.0,0.0,0.814626,0.0,0.0,0.439494
min,1.000000,0.170000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.000000,0.0,0.0,0.000000,0.0,0.0,0.000000
25%,328.000000,22.000000,7.895800,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.000000,0.0,0.0,1.000000,0.0,0.0,0.000000
50%,655.000000,28.000000,14.454200,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,0.000000
75%,982.000000,35.000000,31.275000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000
max,1309.000000,80.000000,512.329200,1.000000,8.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.000000,0.0,0.0,2.000000,0.0,0.0,1.000000

In [9]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [23]:
pd.read_csv('train_and_test2.csv')

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,0,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [24]:
df.shape

(1309, 28)

In [25]:


df = pd.read_csv(
    "train_and_test2.csv",
    converters={"Sex": lambda x: 0 if x == "female" else 1}
)

print(df.head())

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    1      1     0       0       0       0
1            2  38.0  71.2833    1      1     0       0       0       0
2            3  26.0   7.9250    1      0     0       0       0       0
3            4  35.0  53.1000    1      1     0       0       0       0
4            5  35.0   8.0500    1      0     0       0       0       0

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0
1       0  ...        0        0        0       1        0        0       0.0
2       0  ...        0        0        0       3        0        0       2.0
3       0  ...        0        0        0       1        0        0       2.0
4       0  ...        0        0        0       3        0        0       2.0

   zero.17  zero.18  2urvived
0        0        0         0
1        0        0         1
2        0        0         1
3        0        0         1
4        0        0         0

[5 rows x 28 columns]

In [26]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,1,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,1,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [27]:
df["Sex"] = df["Sex"].map({0: "male", 1: "female"})

In [28]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   str
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(24), str(1)
memory usage: 286.5 KB

In [29]:
df

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,female,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,female,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,female,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,female,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,female,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [30]:
pdf=pd.read_csv('train_and_test2.csv')

In [31]:
pdf.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [32]:
pdf["Sex"] = pdf["Sex"].map({0: "male", 1: "female"})

In [33]:
pdf.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,male,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,female,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,female,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,male,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [34]:
vivek=pd.read_csv('train_and_test2.csv',nrows=50)

In [35]:
vivek

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
1,2,38,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
2,3,26,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,1
3,4,35,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,1
4,5,35,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
5,6,28,8.4583,0,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,0
6,7,54,51.8625,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,0
7,8,2,21.0750,0,3,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
8,9,27,11.1333,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,1
9,10,14,30.0708,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
10,11,4,16.7000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,1
11,12,58,26.5500,1,0,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,1
12,13,20,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
13,14,39,31.2750,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
14,15,14,7.8542,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
15,16,55,16.0000,1,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,1
16,17,2,29.1250,0,4,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,0
17,18,28,13.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,1
18,19,31,18.0000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
19,20,28,7.2250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,1
20,21,35,26.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,0
21,22,34,13.0000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,1
22,23,15,8.0292,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,1
23,24,28,35.5000,0,0,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,1
24,25,8,21.0750,1,3,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
25,26,38,31.3875,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,1
26,27,28,7.2250,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
27,28,19,263.0000,0,3,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,0
28,29,28,7.8792,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,1
29,30,28,7.8958,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
30,31,40,27.7208,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
31,32,28,146.5208,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,1
32,33,28,7.7500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,1
33,34,66,10.5000,0,0,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,0
34,35,28,82.1708,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
35,36,42,52.0000,0,1,0,0,0,0,0,...,0,0,0,1,0,0,2,0,0,0
36,37,28,7.2292,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,1
37,38,21,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
38,39,18,18.0000,1,2,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
39,40,14,11.2417,1,1,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,1
40,41,40,9.4750,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
41,42,27,21.0000,1,1,0,0,0,0,0,...,0,0,0,2,0,0,2,0,0,0
42,43,28,7.8958,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
43,44,3,41.5792,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
44,45,19,7.8792,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,1
45,46,28,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0
46,47,28,15.5000,0,1,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,0
47,48,28,7.7500,1,0,0,0,0,0,0,...,0,0,0,3,0,0,1,0,0,1
48,49,28,21.6792,0,2,0,0,0,0,0,...,0,0,0,3,0,0,0,0,0,0
49,50,18,17.8000,1,1,0,0,0,0,0,...,0,0,0,3,0,0,2,0,0,0

In [36]:
vivek.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  50 non-null     int64
 1   Age          50 non-null     int64
 2   Fare         50 non-null     float64
 3   Sex          50 non-null     int64
 4   sibsp        50 non-null     int64
 5   zero         50 non-null     int64
 6   zero.1       50 non-null     int64
 7   zero.2       50 non-null     int64
 8   zero.3       50 non-null     int64
 9   zero.4       50 non-null     int64
 10  zero.5       50 non-null     int64
 11  zero.6       50 non-null     int64
 12  Parch        50 non-null     int64
 13  zero.7       50 non-null     int64
 14  zero.8       50 non-null     int64
 15  zero.9       50 non-null     int64
 16  zero.10      50 non-null     int64
 17  zero.11      50 non-null     int64
 18  zero.12      50 non-null     int64
 19  zero.13      50 non-null     int64
 20  zero.14      50 non-null     int64
 21  Pclass       50 non-null     int64
 22  zero.15      50 non-null     int64
 23  zero.16      50 non-null     int64
 24  Embarked     50 non-null     int64
 25  zero.17      50 non-null     int64
 26  zero.18      50 non-null     int64
 27  2urvived     50 non-null     int64
dtypes: float64(1), int64(27)
memory usage: 11.1 KB

In [46]:
import pandas as pd

df = pd.read_csv('train_and_test2.csv', dtype={'Sex': 'string'})

In [47]:
vivek.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  50 non-null     int64
 1   Age          50 non-null     int64
 2   Fare         50 non-null     float64
 3   Sex          50 non-null     int64
 4   sibsp        50 non-null     int64
 5   zero         50 non-null     int64
 6   zero.1       50 non-null     int64
 7   zero.2       50 non-null     int64
 8   zero.3       50 non-null     int64
 9   zero.4       50 non-null     int64
 10  zero.5       50 non-null     int64
 11  zero.6       50 non-null     int64
 12  Parch        50 non-null     int64
 13  zero.7       50 non-null     int64
 14  zero.8       50 non-null     int64
 15  zero.9       50 non-null     int64
 16  zero.10      50 non-null     int64
 17  zero.11      50 non-null     int64
 18  zero.12      50 non-null     int64
 19  zero.13      50 non-null     int64
 20  zero.14      50 non-null     int64
 21  Pclass       50 non-null     int64
 22  zero.15      50 non-null     int64
 23  zero.16      50 non-null     int64
 24  Embarked     50 non-null     int64
 25  zero.17      50 non-null     int64
 26  zero.18      50 non-null     int64
 27  2urvived     50 non-null     int64
dtypes: float64(1), int64(27)
memory usage: 11.1 KB

In [48]:
df = pd.read_csv('train_and_test2.csv')

df["Sex"] = df["Sex"].map({0: "male", 1: "female"})

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Passengerid  1309 non-null   int64
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   str
 4   sibsp        1309 non-null   int64
 5   zero         1309 non-null   int64
 6   zero.1       1309 non-null   int64
 7   zero.2       1309 non-null   int64
 8   zero.3       1309 non-null   int64
 9   zero.4       1309 non-null   int64
 10  zero.5       1309 non-null   int64
 11  zero.6       1309 non-null   int64
 12  Parch        1309 non-null   int64
 13  zero.7       1309 non-null   int64
 14  zero.8       1309 non-null   int64
 15  zero.9       1309 non-null   int64
 16  zero.10      1309 non-null   int64
 17  zero.11      1309 non-null   int64
 18  zero.12      1309 non-null   int64
 19  zero.13      1309 non-null   int64
 20  zero.14      1309 non-null   int64
 21  Pclass       1309 non-null   int64
 22  zero.15      1309 non-null   int64
 23  zero.16      1309 non-null   int64
 24  Embarked     1307 non-null   float64
 25  zero.17      1309 non-null   int64
 26  zero.18      1309 non-null   int64
 27  2urvived     1309 non-null   int64
dtypes: float64(3), int64(24), str(1)
memory usage: 286.5 KB

In [49]:
df.rename(columns={"Sex": "Gender"}, inplace=True)

In [52]:
df

,Passengerid,Age,Fare,Gender,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,male,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,female,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,female,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,female,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,male,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,1305,28.0,8.0500,male,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1305,1306,39.0,108.9000,female,0,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,0
1306,1307,38.5,7.2500,male,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1307,1308,28.0,8.0500,male,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1308,1309,28.0,22.3583,male,1,0,0,0,0,0,...,0,0,0,3,0,0,0.0,0,0,0

In [53]:
df = pd.read_csv("train_and_test2.csv", on_bad_lines="warn")

In [54]:
df = pd.read_csv("train_and_test2.csv", on_bad_lines="skip")

In [59]:
new = pd.read_csv("train_and_test2.csv", usecols=["Age"])

In [60]:
new

       Age
0     22.0
1     38.0
2     26.0
3     35.0
4     35.0
...    ...
1304  28.0
1305  39.0
1306  38.5
1307  28.0
1308  28.0

[1309 rows x 1 columns]

In [62]:
df=pd.read_csv('train_and_test.csv',usecols=['Age'],squeeze=True)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [63]:
df.iloc[5]

Passengerid     6.0000
Age            28.0000
Fare            8.4583
Sex             0.0000
sibsp           0.0000
zero            0.0000
zero.1          0.0000
zero.2          0.0000
zero.3          0.0000
zero.4          0.0000
zero.5          0.0000
zero.6          0.0000
Parch           0.0000
zero.7          0.0000
zero.8          0.0000
zero.9          0.0000
zero.10         0.0000
zero.11         0.0000
zero.12         0.0000
zero.13         0.0000
zero.14         0.0000
Pclass          3.0000
zero.15         0.0000
zero.16         0.0000
Embarked        1.0000
zero.17         0.0000
zero.18         0.0000
2urvived        0.0000
Name: 5, dtype: float64

In [64]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

titanic = pd.read_csv(url)

print(titanic.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S